/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CaregiverRouteImport } from './routes/caregiver'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth.verify-email'
import { Route as AuthVerifyOtpRouteImport } from './routes/auth.verify-otp'
import { Route as CaregiverIndexRouteImport } from './routes/caregiver.index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as PatientAnalyticsRouteImport } from './routes/patient.analytics'
import { Route as PatientAssistantRouteImport } from './routes/patient.assistant'
import { Route as PatientCalendarRouteImport } from './routes/patient.calendar'
import { Route as PatientNotificationsRouteImport } from './routes/patient.notifications'
import { Route as PatientOcrRouteImport } from './routes/patient.ocr'
import { Route as PatientProfileRouteImport } from './routes/patient.profile'
import { Route as PatientRefillsRouteImport } from './routes/patient.refills'
import { Route as PatientRemindersRouteImport } from './routes/patient.reminders'
import { Route as PatientSettingsRouteImport } from './routes/patient.settings'
import { Route as PatientMedicinesIndexRouteImport } from './routes/patient.medicines.index'
import { Route as PatientMedicinesAddRouteImport } from './routes/patient.medicines.add'
import { Route as PatientMedicinesEditIdRouteImport } from './routes/patient.medicines.edit.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverRoute = CaregiverRouteImport.update({
  id: '/caregiver',
  path: '/caregiver',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthRoute,
} as any)
const CaregiverIndexRoute = CaregiverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaregiverRoute,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAnalyticsRoute = PatientAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAssistantRoute = PatientAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => PatientRoute,
} as any)
const PatientCalendarRoute = PatientCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => PatientRoute,
} as any)
const PatientNotificationsRoute = PatientNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PatientRoute,
} as any)
const PatientOcrRoute = PatientOcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => PatientRoute,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PatientRoute,
} as any)
const PatientRefillsRoute = PatientRefillsRouteImport.update({
  id: '/refills',
  path: '/refills',
  getParentRoute: () => PatientRoute,
} as any)
const PatientRemindersRoute = PatientRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => PatientRoute,
} as any)
const PatientSettingsRoute = PatientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PatientRoute,
} as any)
const PatientMedicinesIndexRoute = PatientMedicinesIndexRouteImport.update({
  id: '/medicines/',
  path: '/medicines/',
  getParentRoute: () => PatientRoute,
} as any)
const PatientMedicinesAddRoute = PatientMedicinesAddRouteImport.update({
  id: '/medicines/add',
  path: '/medicines/add',
  getParentRoute: () => PatientRoute,
} as any)
const PatientMedicinesEditIdRoute = PatientMedicinesEditIdRouteImport.update({
  id: '/medicines/edit/$id',
  path: '/medicines/edit/$id',
  getParentRoute: () => PatientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/caregiver': typeof CaregiverRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/patient/analytics': typeof PatientAnalyticsRoute
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/calendar': typeof PatientCalendarRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/ocr': typeof PatientOcrRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/refills': typeof PatientRefillsRoute
  '/patient/reminders': typeof PatientRemindersRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/caregiver/': typeof CaregiverIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/patient/medicines/add': typeof PatientMedicinesAddRoute
  '/patient/medicines/': typeof PatientMedicinesIndexRoute
  '/patient/medicines/edit/$id': typeof PatientMedicinesEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/patient/analytics': typeof PatientAnalyticsRoute
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/calendar': typeof PatientCalendarRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/ocr': typeof PatientOcrRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/refills': typeof PatientRefillsRoute
  '/patient/reminders': typeof PatientRemindersRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/caregiver': typeof CaregiverIndexRoute
  '/patient': typeof PatientIndexRoute
  '/patient/medicines/add': typeof PatientMedicinesAddRoute
  '/patient/medicines': typeof PatientMedicinesIndexRoute
  '/patient/medicines/edit/$id': typeof PatientMedicinesEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/caregiver': typeof CaregiverRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/patient/analytics': typeof PatientAnalyticsRoute
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/calendar': typeof PatientCalendarRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/ocr': typeof PatientOcrRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/refills': typeof PatientRefillsRoute
  '/patient/reminders': typeof PatientRemindersRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/caregiver/': typeof CaregiverIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/patient/medicines/add': typeof PatientMedicinesAddRoute
  '/patient/medicines/': typeof PatientMedicinesIndexRoute
  '/patient/medicines/edit/$id': typeof PatientMedicinesEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/caregiver'
    | '/patient'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/auth/verify-otp'
    | '/patient/analytics'
    | '/patient/assistant'
    | '/patient/calendar'
    | '/patient/notifications'
    | '/patient/ocr'
    | '/patient/profile'
    | '/patient/refills'
    | '/patient/reminders'
    | '/patient/settings'
    | '/admin/'
    | '/caregiver/'
    | '/patient/'
    | '/patient/medicines/add'
    | '/patient/medicines/'
    | '/patient/medicines/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/auth/verify-otp'
    | '/patient/analytics'
    | '/patient/assistant'
    | '/patient/calendar'
    | '/patient/notifications'
    | '/patient/ocr'
    | '/patient/profile'
    | '/patient/refills'
    | '/patient/reminders'
    | '/patient/settings'
    | '/admin'
    | '/caregiver'
    | '/patient'
    | '/patient/medicines/add'
    | '/patient/medicines'
    | '/patient/medicines/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/caregiver'
    | '/patient'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/auth/verify-otp'
    | '/patient/analytics'
    | '/patient/assistant'
    | '/patient/calendar'
    | '/patient/notifications'
    | '/patient/ocr'
    | '/patient/profile'
    | '/patient/refills'
    | '/patient/reminders'
    | '/patient/settings'
    | '/admin/'
    | '/caregiver/'
    | '/patient/'
    | '/patient/medicines/add'
    | '/patient/medicines/'
    | '/patient/medicines/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CaregiverRoute: typeof CaregiverRouteWithChildren
  PatientRoute: typeof PatientRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver': {
      id: '/caregiver'
      path: '/caregiver'
      fullPath: '/caregiver'
      preLoaderRoute: typeof CaregiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/verify-otp': {
      id: '/auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/auth/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/caregiver/': {
      id: '/caregiver/'
      path: '/'
      fullPath: '/caregiver/'
      preLoaderRoute: typeof CaregiverIndexRouteImport
      parentRoute: typeof CaregiverRoute
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/analytics': {
      id: '/patient/analytics'
      path: '/analytics'
      fullPath: '/patient/analytics'
      preLoaderRoute: typeof PatientAnalyticsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/assistant': {
      id: '/patient/assistant'
      path: '/assistant'
      fullPath: '/patient/assistant'
      preLoaderRoute: typeof PatientAssistantRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/calendar': {
      id: '/patient/calendar'
      path: '/calendar'
      fullPath: '/patient/calendar'
      preLoaderRoute: typeof PatientCalendarRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/notifications': {
      id: '/patient/notifications'
      path: '/notifications'
      fullPath: '/patient/notifications'
      preLoaderRoute: typeof PatientNotificationsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/ocr': {
      id: '/patient/ocr'
      path: '/ocr'
      fullPath: '/patient/ocr'
      preLoaderRoute: typeof PatientOcrRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/refills': {
      id: '/patient/refills'
      path: '/refills'
      fullPath: '/patient/refills'
      preLoaderRoute: typeof PatientRefillsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/reminders': {
      id: '/patient/reminders'
      path: '/reminders'
      fullPath: '/patient/reminders'
      preLoaderRoute: typeof PatientRemindersRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/settings': {
      id: '/patient/settings'
      path: '/settings'
      fullPath: '/patient/settings'
      preLoaderRoute: typeof PatientSettingsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/medicines/': {
      id: '/patient/medicines/'
      path: '/medicines'
      fullPath: '/patient/medicines/'
      preLoaderRoute: typeof PatientMedicinesIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/medicines/add': {
      id: '/patient/medicines/add'
      path: '/medicines/add'
      fullPath: '/patient/medicines/add'
      preLoaderRoute: typeof PatientMedicinesAddRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/medicines/edit/$id': {
      id: '/patient/medicines/edit/$id'
      path: '/medicines/edit/$id'
      fullPath: '/patient/medicines/edit/$id'
      preLoaderRoute: typeof PatientMedicinesEditIdRouteImport
      parentRoute: typeof PatientRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CaregiverRouteChildren {
  CaregiverIndexRoute: typeof CaregiverIndexRoute
}

const CaregiverRouteChildren: CaregiverRouteChildren = {
  CaregiverIndexRoute: CaregiverIndexRoute,
}

const CaregiverRouteWithChildren = CaregiverRoute._addFileChildren(
  CaregiverRouteChildren,
)

interface PatientRouteChildren {
  PatientAnalyticsRoute: typeof PatientAnalyticsRoute
  PatientAssistantRoute: typeof PatientAssistantRoute
  PatientCalendarRoute: typeof PatientCalendarRoute
  PatientNotificationsRoute: typeof PatientNotificationsRoute
  PatientOcrRoute: typeof PatientOcrRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientRefillsRoute: typeof PatientRefillsRoute
  PatientRemindersRoute: typeof PatientRemindersRoute
  PatientSettingsRoute: typeof PatientSettingsRoute
  PatientIndexRoute: typeof PatientIndexRoute
  PatientMedicinesAddRoute: typeof PatientMedicinesAddRoute
  PatientMedicinesIndexRoute: typeof PatientMedicinesIndexRoute
  PatientMedicinesEditIdRoute: typeof PatientMedicinesEditIdRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientAnalyticsRoute: PatientAnalyticsRoute,
  PatientAssistantRoute: PatientAssistantRoute,
  PatientCalendarRoute: PatientCalendarRoute,
  PatientNotificationsRoute: PatientNotificationsRoute,
  PatientOcrRoute: PatientOcrRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientRefillsRoute: PatientRefillsRoute,
  PatientRemindersRoute: PatientRemindersRoute,
  PatientSettingsRoute: PatientSettingsRoute,
  PatientIndexRoute: PatientIndexRoute,
  PatientMedicinesAddRoute: PatientMedicinesAddRoute,
  PatientMedicinesIndexRoute: PatientMedicinesIndexRoute,
  PatientMedicinesEditIdRoute: PatientMedicinesEditIdRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CaregiverRoute: CaregiverRouteWithChildren,
  PatientRoute: PatientRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
